### ISSUE TITLE
Deploy button doesn't work. Can't start the app.

### ISSUE THREAD

**Issue by kondranton** [IBM-Bluemix/bluemix-python-flask-sample#5]
Here is my log file:

Downloading artifacts...DOWNLOAD SUCCESSFUL
Target: https://api.eu-gb.bluemix.net
Using manifest file /home/pipeline/7d8db3b4-095b-4c58-a4af-19cfd3b03bb2/manifest.yml

Creating app bluemix-python-flask-sample-helloworldapp-1410 in org kondrashka1313@yandex.ru / space dev as kondrashka1313@yandex.ru...
OK

Using route bluemix-python-flask-sample-helloworldapp-1410.eu-gb.mybluemix.net
Binding bluemix-python-flask-sample-helloworldapp-1410.eu-gb.mybluemix.net to bluemix-python-flask-sample-helloworldapp-1410...
OK

Uploading bluemix-python-flask-sample-helloworldapp-1410...
Uploading app files from: /home/pipeline/7d8db3b4-095b-4c58-a4af-19cfd3b03bb2
Uploading 34.4K, 15 files

                             
Done uploading
OK

Starting app bluemix-python-flask-sample-helloworldapp-1410 in org kondrashka1313@yandex.ru / space dev as kondrashka1313@yandex.ru...
-----> Downloaded app package (24K)
-------> Buildpack version 1.5.1
-----> Installing runtime (python-2.7.11)
-----> Installing dependencies with pip
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "/app/.heroku/python/bin/pip", line 9, in <module>
    load_entry_point('pip==7.1.0', 'console_scripts', 'pip')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 558, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2682, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2355, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2361, in resolve
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.1.0-py2.7.egg/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.1.0-py2.7.egg/pip/vcs/mercurial.py", line 10, in <module>
    from pip.download import path_to_url
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.1.0-py2.7.egg/pip/download.py", line 38, in <module>
    from pip._vendor import requests, six
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.1.0-py2.7.egg/pip/_vendor/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.1.0-py2.7.egg/pip/_vendor/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.1.0-py2.7.egg/pip/_vendor/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.1.0-py2.7.egg/pip/_vendor/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.1.0-py2.7.egg/pip/_vendor/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.1.0-py2.7.egg/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 31, in <module>
    from .connection import (
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.1.0-py2.7.egg/pip/_vendor/requests/packages/urllib3/connection.py", line 45, in <module>
    from .util.ssl_ import (
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.1.0-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/__init__.py", line 5, in <module>
    from .ssl_ import (
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.1.0-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py", line 2, in <module>
    from hashlib import md5, sha1, sha256
ImportError: cannot import name md5
Staging failed: Buildpack compilation step failed

FAILED
BuildpackCompileFailed

TIP: use 'cf logs bluemix-python-flask-sample-helloworldapp-1410 --recent' for more information

Finished: FAILED

**Comment by kondranton** [comment]
And I have the same problem in console.
